domain_path: C:\Users\CK\Desktop\VIVADO_PROJECTS\ZC702_EVK\Zynq7020_Vitis\zynq_perf\export\zynq_perf\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.2\Vitis\data\embeddedsw\lib\sw_apps\lwip_tcp_perf_server
template: lwip_tcp_perf_server
lang: c
