domain_path: C:\Users\CK\Desktop\Workspace\Vitis_Workspace\ZC702_Zynq\zynq_arm_perf\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\2025.2\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
