domain_path: C:\Users\CK\Desktop\Workspace\Vitis_Workspace\ZC702_Zynq\zynq_arm_perf\export\zynq_arm_perf\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.2\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
